apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: default # Там, де живе твій бекенд
  labels:
    # КРИТИЧНО: Ця мітка каже Helm-чарту Prometheus, що цей монітор треба взяти в роботу
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: backend # Має чітко збігатися з міткою (labels) у Service вашого бекенду
  endpoints:
    - port: http # Назва порту, яку ми щойно прописали в Service бекенду
      interval: 15s # Як часто Прометеус буде смикати додаток
      # Оскільки твій роутер підключено з префіксом /api, шлях до метрик буде саме таким:
      path: /api/metrics