apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring # <--- 1. ПЕРЕНОСИМО В НЕЙМСПЕЙС ПРОМЕТЕУСА
  labels:
    release: monitoring
spec:
  # --- 2. ДОДАЄМО ВКАЗІВНИК НА НЕЙМСПЕЙС ДОДАТКА ---
  namespaceSelector:
    matchNames:
      - default 
  # ------------------------------------------------
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      interval: 15s
      path: /api/metrics