apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          persistence:
            enabled: false
        promtail:
          enabled: true
          resources:
            limits:
              memory: 256Mi
        grafana:
          enabled: false
        prometheus:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true