apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2 # Актуальна стабільна версія чарту
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          #  Жорсткі ліміти, щоб Loki не "з'їв" усю пам'ять на твоїх e2-standard-4
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          persistence:
            enabled: false # Для портфоліо зберігаємо логи в оперативній пам'яті (без постійного диска)
        promtail:
          enabled: true
          # Promtail теж обмежуємо
          resources:
            limits:
              memory: 256Mi
        grafana:
          enabled: false # У нас вже є своя Графана з Dex
        prometheus:
          enabled: false # Прометеус у нас теж уже є
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Розгортаємо туди ж, де лежить наш моніторинг
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true