apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kavallerya/devops-cv-app-infra.git' # Обов'язково замініть логін!
    targetRevision: HEAD          # Завжди дивитися на останній коміт у гілці
    path: k8s                     # Папка, де лежать ваші бекенд, фронтенд і external-secrets
  destination:
    server: 'https://kubernetes.default.svc' # Розгортати в цей самий кластер
    namespace: default            # Куди селити ваш додаток
  syncPolicy:
    automated:
      prune: true                 # Видаляти з кластера те, що ви видалили з Git
      selfHeal: true              # Повертати як було, якщо хтось ручками щось змінив у кластері
    syncOptions:
      - CreateNamespace=true
