apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Кажемо Google Cloud створити класичний балансувальник
    kubernetes.io/ingress.class: "gce"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Використовуємо сертифікат від Let's Encrypt
  
spec:
  tls:
  - hosts:
    - imorozov.xyz
    - api.imorozov.xyz
    secretName: cv-tls-secret # Ім'я секрету для TLS
  rules:
  - host: imorozov.xyz
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: api.imorozov.xyz
    http:
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 8000