apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io' # Офіційний репозиторій чартів
    chart: cert-manager
    targetRevision: v1.14.0 # Стабільна ентерпрайз версія
    helm:
      parameters:
        - name: installCRDs
          value: "true" # КРИТИЧНО: вчить Кубернетес слову ClusterIssuer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager # Сам створить цей неймсейс
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true