apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.dexidp.io'
    chart: dex
    targetRevision: 0.19.1
    helm:
      valuesObject:
        envFrom:
          - secretRef:
              name: dex-env-secrets

        config:
          issuer: https://auth.imorozov.xyz

          storage:
            type: kubernetes
            config:
              inCluster: true

          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: $GITHUB_CLIENT_ID
                clientSecret: $GITHUB_CLIENT_SECRET
                redirectURI: https://auth.imorozov.xyz/callback
                loadAllGroups: true
                orgs:
                  - name: imorozov-infra
                    teams:
                      - devops

          staticClients:
            - id: grafana
              name: 'Grafana Dashboard'
              redirectURIs:
                - https://monitor.imorozov.xyz/login/generic_oauth
              secretEnv: GRAFANA_SHARED_SECRET

        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: auth.imorozov.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            - secretName: dex-tls-secret
              hosts:
                - auth.imorozov.xyz
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true