apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      # Замість parameters використовуємо valuesObject для складної конфігурації
      valuesObject:
        coreDns:
          enabled: false # Вимикаємо CoreDNS, бо він вже є в кластері
        kubeDns:
          enabled: false # Вимикаємо KubeDNS, бо він вже є в кластері
        grafana:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - monitor.imorozov.xyz
            tls:
              - secretName: grafana-tls-secret
                hosts:
                  - monitor.imorozov.xyz
          # 1. Прокидаємо секрет з K8s як змінну оточення в под Графани
          envValueFrom:
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-dex-client-secret
                key: dex-client-secret
          
          # 2. Налаштовуємо саму Графану
          grafana.ini:
            server:
              root_url: https://monitor.imorozov.xyz # Важливо для колбеків
            auth.generic_oauth:
              enabled: true
              name: "GitHub (via Dex)"
              allow_sign_up: true
              client_id: grafana
              # Графана візьме секрет зі змінної оточення, яку ми прокинули вище
              client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
              scopes: "openid profile email groups"
              # Front-channel залишаємо зовнішнім (для браузера)
              auth_url: "https://auth.imorozov.xyz/auth"
              # Back-channel переводимо у внутрішню мережу K8s (без SSL, напряму)
              token_url: "http://dex.dex.svc.cluster.local:5556/token"
              api_url: "http://dex.dex.svc.cluster.local:5556/userinfo"
              allow_assign_grafana_admin: true # Дозволяємо призначати ролі через Dex

              role_attribute_path: "contains(groups[*], 'imorozov-infra:devops') && 'Admin' || 'Viewer'" # Призначаємо роль на основі групи в GitHub
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true