apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      valuesObject:
        coreDns:
          enabled: false
        kubeDns:
          enabled: false
        grafana:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - monitor.imorozov.xyz
            tls:
              - secretName: grafana-tls-secret
                hosts:
                  - monitor.imorozov.xyz
          envValueFrom:
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-dex-client-secret
                key: dex-client-secret

          grafana.ini:
            server:
              root_url: https://monitor.imorozov.xyz
            auth.generic_oauth:
              enabled: true
              name: "GitHub (via Dex)"
              allow_sign_up: true
              client_id: grafana
              client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
              scopes: "openid profile email groups"
              auth_url: "https://auth.imorozov.xyz/auth"
              token_url: "http://dex.dex.svc.cluster.local:5556/token"
              api_url: "http://dex.dex.svc.cluster.local:5556/userinfo"
              allow_assign_grafana_admin: true
              role_attribute_path: "contains(groups[*], 'imorozov-infra:devops') && 'Admin' || 'Viewer'"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true