apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cv-db-secret
  namespace: default
spec:
  refreshInterval: "1h" # Перевіряти оновлення пароля кожну годину
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: app-db-secret # Цю назву ви потім пропишете у вашому бекенді
    creationPolicy: Owner
  data:
    - secretKey: database_password # Ключ всередині K8s Secret
      remoteRef:
        key: cv-db-password       # Назва секрету в GCP Secret Manager