apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: cv-k8s-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cv-db-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: database_password
      remoteRef:
        key: cv-db-password