apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets-sync
  namespace: dex # Секрет має лежати там, де житиме сам Dex
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: dex-env-secrets # Ім'я K8s Secret, який створиться автоматично
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: dex-github-creds
        property: github-client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: dex-github-creds
        property: github-client-secret
    - secretKey: GRAFANA_SHARED_SECRET
      remoteRef:
        key: dex-github-creds
        property: shared-grafana-secret