# 1. Описуємо "Джерело": де саме в Google Cloud лежать секрети
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: cv-k8s-prod # ЗАМІНИ НА СВІЙ ID (наприклад, my-project-123)
---
# 2. Описуємо "Запит": який саме секрет нам потрібен
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-sync
spec:
  refreshInterval: 1h             # Як часто перевіряти оновлення в Google Cloud
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: db-credentials          # ТАК буде називатися секрет усередині Kubernetes
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD        # Ключ усередині K8s Secret
    remoteRef:
      key: db-password            # Назва секрету в Google Secret Manager