apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-dex-auth
  namespace: monitoring # КРИТИЧНО: Кладемо туди, де живе моніторинг
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: grafana-dex-client-secret
    creationPolicy: Owner
  data:
    - secretKey: dex-client-secret
      remoteRef:
        key: dex-github-creds
        property: shared-grafana-secret